name: Test build msi

on: [push, pull_request]

jobs:
  test_build_msi:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Build msi
        shell: pwsh
        run: |
          uv run python setup.py build
          uv run python setup.py bdist_msi
